### ISSUE TITLE
Debug info gets cut off

### ISSUE THREAD

**Issue by aidancrowther** [aidancrowther/ASCIIPlay#11]
Debug info displays normally on a 1080p display, but when downsizing the output for smaller windows it gets cut off at the top. This should be a relatively easy fix using the already found scaling offsets. All modifications need to be made in renderer.c

**Comment by AshkanArabim** [comment]
I can't seem to recreate the issue even on a very small frame. (see how the subtitle is barely fitting)

It seems like everything that appears in `renderer.c` for debug mode is showing up properly:
| col 1    | col 2        | col 3 |
| -------- | ------------ | ----- |
| time     |              |       |
| time (realtime)     |              |       |
| next sub |              |       |
| sub ends | sub file ptr |       |
| sub line | array idx    |       |
| width    | height       |       |
| r_width  | r_height     | scale |


![image](https://github.com/aidancrowther/ASCIIPlay/assets/71609332/a93ecd92-e4c1-4514-be28-b26dee3dd18f)

**Comment by aidancrowther** [comment]
This was likely an artifact of the old window resizer, will close until it is observed again
