### ISSUE TITLE
Terminal cursor disappears after running the program

### ISSUE THREAD

**Issue by AshkanArabim** [aidancrowther/ASCIIPlay#15]
Whenever I try to run the program (although I still havent managed to get it to actually play something) and exit by using `ctrl -c`, my terminal's cursor disappears. I can only revert it back to a normal state through the `reset` command. 

Here's a command I use to open a sample video and subtitle combo: 

`./telnetflix -f ../sample_video/webcam.mp4 -s ../sample_video/sample.srt`

Steps to reproduce:
- Run the program with the `-f` followed by the location of your video file.
- Exit through ctrl + C.

Edit: typo

**Comment by AngelOnFira** [comment]
I know some funky stuff happens with ncurses, so I'd bet that it's not being cleaned after closing

**Comment by aidancrowther** [comment]
This is correct, if the program terminated normally, it will clean up and release ncurses, returning the cursor. If it is interrupted it is unable to perform this cleanup. I will look at adding a control input to allow early playback termination

**Comment by Skote2** [comment]
Fixed by #17 (mostly, this is what happens whenever the shell crashes, and will happen again if it crashes for any other reasons. It's expected that being unable to clean up will break the shell though so it's kind of a fixed, kind of a won't fix)
