### ISSUE TITLE
Segmentation Fault when opening video files

### ISSUE THREAD

**Issue by AshkanArabim** [aidancrowther/ASCIIPlay#16]
When I try to open a video, I get a segmentation fault. I've tried to open two video files, where one uses the MPEG-4 (h.264) codec and the other uses the HEVC (h.265) codec. 

Steps to reproduce:
- run `./telnetflix -f [your_fil_here]`

**Comment by aidancrowther** [comment]
As mentioned by Skote, please try to run using the delay flag. This will at least allow you to test the system until we have properly fixed the producer/consumer system

**Comment by Skote2** [comment]
fixed by #17
